spring.application.name=SpringBootExam001-OnlinePaymentProcessingSystem

spring.profiles.active=international
gateway=Paypal
charge=3.5
currency=USD

#spring.profiles.active=india
#gateway=Razorpay
#charge=2.5
#currency=INR


