package com.nt.service;

import org.springframework.stereotype.Service;

import com.nt.model.TravelPackage;
import com.nt.repository.TravelPackageRepository;

import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

@Service
public class TravelPackageServiceImpl implements TravelPackageService {

	private final TravelPackageRepository repository;

	public TravelPackageServiceImpl(TravelPackageRepository repository) {
		this.repository = repository;
	}

	@Override
	public Mono<TravelPackage> createPackage(TravelPackage travelPackage) {

		// ID is generated by MySQL AUTO_INCREMENT
		travelPackage.setPackageId(null);

		return repository.save(travelPackage);
	}

	@Override
	public Flux<TravelPackage> getAllPackages() {
		return repository.findAll();
	}

	@Override
	public Mono<TravelPackage> getPackageById(Integer id) {
		return repository.findById(id);
	}

	@Override
	public Mono<TravelPackage> updatePackage(Integer id, TravelPackage travelPackage) {

		return repository.findById(id).flatMap(existingPackage -> {

			existingPackage.setPackageName(travelPackage.getPackageName());

			existingPackage.setDestination(travelPackage.getDestination());

			existingPackage.setPrice(travelPackage.getPrice());

			existingPackage.setDuration(travelPackage.getDuration());

			return repository.save(existingPackage);
		});
	}

	@Override
	public Mono<Void> deletePackage(Integer id) {
		return repository.deleteById(id);
	}
}