spring.application.name=SpringBootE016-jms-DailyReportEmailSender

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=anandraj24092002@gmail.com
spring.mail.password=jxsfmxxjssgeykqk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true