spring.application.name=RESTAPI007-SpringWebFlux-CRUD-TravelPackage

server.port=8080

# Reactive MySQL / R2DBC connection
spring.r2dbc.url=r2dbc:mysql://localhost:3306/travel_db
spring.r2dbc.username=root
spring.r2dbc.password=root

# Initialize schema.sql
spring.sql.init.mode=always

# Logging
logging.level.org.springframework.r2dbc=DEBUG