spring.application.name=SpringBoot014-ProductRepositorySystem

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/FREE
spring.datasource.username=spring
spring.datasource.password=123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.hibernate.ddl-auto=update
