spring.application.name=SpringBootExam003-UniversityAdmissionManagement

university.id=101
university.name=National University
university.location=Hyderabad
university.admissionFee=5000
university.contact=9876543210
university.website=www.nationaluniversity.com