spring.application.name=SpringBootExam005-EmployeePerformanceBonus

employee.id=101
employee.name=Arun
employee.salary=60000
employee.rating=4.5
employee.experience=6

#spring.profiles.active=senior
spring.profiles.active=junior